CIRCUITPY_WIFI_SSID = "OLIN-DEVICES"
CIRCUITPY_WIFI_PASSWORD = "Engineering4Every1!"
CIRCUITPY_WEB_API_PASSWORD = "passw0rd"
CIRCUITPY_WEB_API_PORT = 80
AIO_USERNAME = "cory0417"
AIO_KEY = "aio_EYSQ21QspSBqTwczmojexf8T51oM"
